### ISSUE TITLE
Problem loading Bodleian manifests

### ISSUE THREAD

**Issue by ahankinson** [durham-university/jalava#1]
This is a great collection browser! 

When I load the Bodleian collections, however, it seems to have a problem parsing the manifests; none of them will load.

**Comment by ojlyytinen** [comment]
Thanks for reporting this. I've fixed this in 7cf5190 and they should work now. The issue was that it was reading logo as a simple string rather than a service.

I suspect there may be other similar issues as I built the IIIF decoder to handle the manifests I could find and not much more rather than trying to make it fully standards compliant. This is still just a prototype after all.
